---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-solution.html 
keywords: solution, architecture, details, hardware, software 
summary: このセクションでは、dremio 認証に使用されるハードウェアとソフトウェアについて説明します。この情報は、 NetAppストレージを使用した dremio の展開に適用されます。 
---
= ソリューションの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Hybrid Iceberg Lakehouse ソリューションは、データ レイクの顧客が直面する顧客の課題に対処するための独自の利点を提供します。 Dremio Unified Lakehouse プラットフォームとNetApp ONTAP、 StorageGRID、 NetApp Cloud ソリューションを活用することで、企業はビジネス運営に大きな価値を付加できます。このソリューションは、 NetAppソースを含む複数のデータ ソースへのアクセスを提供するだけでなく、全体的な分析パフォーマンスを向上させ、企業がビジネスの成長につながるビジネス インサイトを獲得できるよう支援します。



== NetAppの概要

* ONTAPやStorageGRIDなどの NetApp の製品は、ストレージとコンピューティングの分離を可能にし、特定の要件に基づいて最適なリソース利用を実現します。この柔軟性により、お客様はNetAppストレージソリューションを使用してストレージを独自に拡張できるようになります。
* NetApp のストレージ コントローラを活用することで、顧客は NFS および S3 プロトコルを使用してベクター データベースにデータを効率的に提供できます。これらのプロトコルは、顧客データの保存を容易にし、ベクター データベース インデックスを管理するため、ファイルやオブジェクトの方法を通じてアクセスされるデータの複数のコピーが不要になります。
* NetApp ONTAP は、AWS、Azure、Google Cloud などの主要なクラウド サービス プロバイダー全体で NAS およびオブジェクト ストレージのネイティブ サポートを提供します。この幅広い互換性により、シームレスな統合が保証され、顧客データのモビリティ、グローバルなアクセス性、災害復旧、動的なスケーラビリティ、高パフォーマンスが実現します。




=== StorageGRID

業界をリードする当社のオブジェクト ストレージ storageGRID は、自動データ配置、柔軟な導入オプション、階層化された消去コーディングによる比類のない耐久性を実現する強力なポリシー エンジンを提供します。単一の名前空間で数十億のオブジェクトとペタバイトのデータをサポートするスケーラブルなアーキテクチャを備えています。このソリューションはハイブリッド クラウド統合を可能にし、主要なクラウド プラットフォームへのデータ階層化を可能にします。  2019 年の IDC Marketscape Worldwide Object-Based Vendor Assessment でリーダーとして認められました。

さらに、storageGRID は、ソフトウェア定義のオブジェクト ストレージ、地理的冗長性、およびマルチサイト機能により、大規模な非構造化データの管理に優れています。ポリシーベースの情報ライフサイクル管理が組み込まれており、ミラーリングや検索などのクラウド統合機能を提供します。  Common Criteria、NF203 Digital Safe Component、ISO/IEC 25051、KPMG、Cohasset Compliance Assessment など、さまざまな認証を取得しています。

要約すると、 NetApp storageGRID は、大規模な非構造化データを効率的に管理するための強力な機能、スケーラビリティ、ハイブリッド クラウド統合、コンプライアンス認定を提供します。



=== NetApp ONTAP

NetApp ONTAPは、幅広いエンタープライズ機能を提供する堅牢なストレージ ソリューションです。これには、アプリケーションの一貫性と改ざん防止を備えた即時バックアップを提供するスナップショットが含まれています。 SnapRestore はオンデマンドでのバックアップのほぼ瞬時の復元を可能にし、 SnapMirror は統合されたリモート バックアップおよび災害復旧機能を提供します。このソリューションには、自律ランサムウェア保護 (ARP) も組み込まれており、複数の管理者による検証、FIPS 認定による保存データの暗号化、転送中のデータの暗号化、多要素認証 (MFA)、ロールベースのアクセス制御 (RBAC) などの機能によってデータのセキュリティを確保します。包括的なログ記録、監査、オンボードおよび外部キー管理、安全な消去、複数のテナントの安全な管理により、データのセキュリティとコンプライアンスがさらに強化されます。

NetApp ONTAP には、低い総所有コストで、高いレベルの整合性、パフォーマンス、保持力を備えた規制に準拠したデータ保持を提供するSnapLockも搭載されています。  NetApp ONTAP 9 と完全に統合されており、悪意のある行為、不正な管理者、ランサムウェアに対する保護を提供します。

このソリューションには、転送中および保存中のデータの暗号化のための NSE/NVE 暗号化、多要素管理者アクセス、および複数管理者検証が含まれます。 Active IQ はAI を活用した予測分析と修正アクションを提供し、QoS はサービス品質のワークロード制御を保証します。管理と自動化の統合は、SysMgr/GUI/CLI/API を通じて直感的に行えます。  FabricPool は自動データ階層化を可能にし、インライン データ圧縮、重複排除、および圧縮を通じて効率性を実現します。  NetApp は、顧客に費用をかけずにワークロード効率の目標を達成することを保証します。

NetApp ONTAP は、NVMe/FC、FC、NVMe/TCP、iSCSI、NFS、SMB、S3 などのさまざまなプロトコルをサポートし、統合ストレージ ソリューションを実現します。全体として、 NetApp ONTAP は、多様なストレージ ニーズを満たすための広範なエンタープライズ機能、強力なセキュリティ、コンプライアンス、効率性、汎用性を提供します。



== Dremioの概要

Dremio は、セルフサービス分析と AI のための統合レイクハウス プラットフォームです。  Dremio 統合分析プラットフォームは、従来のデータ ウェアハウス ソリューションの数分の 1 のコストで、レイクハウスの柔軟性、拡張性、パフォーマンスを実現し、ユーザーをデータに近づけます。  Dremio は、「シフトレフト」分析を可能にして、複雑でコストのかかるデータ統合と ETL を排除し、データ移動のないシームレスなエンタープライズ規模の分析を実現します。  Dremio には以下の機能もあります:

* ユニバーサルなセマンティック レイヤーと緊密に統合された高性能な SQL クエリ エンジンによって実現される使いやすいセルフサービス分析により、クラウドとオンプレミスの両方ですべてのデータの接続、管理、分析が容易になります。
* Dremio の Apache Iceberg ネイティブのレイクハウス管理機能は、データ検出を簡素化し、データ最適化を自動化して、Git にヒントを得たデータ バージョン管理による高性能分析を実現します。
* Dremio はオープンソースとオープン スタンダードに基づいて構築されており、企業がロックインを回避し、イノベーションの態勢を維持できるようにします。エンタープライズ企業は、あらゆるワークロードで最高の価格性能比を備えた、最も使いやすいレイクハウス プラットフォームとして Dremio を信頼しています。




== Dremio とNetApp のハイブリッド Iceberg Lakehouse ソリューションは顧客にどのような価値をもたらしますか?

* *データ管理とアクセス性の向上*: Dremio は、組織がデータ レイクから直接高速にデータをクエリできるようにするデータ レイクハウス プラットフォームでよく知られています。一方、 NetApp は、クラウド データ サービスとデータ ストレージ ソリューションの大手プロバイダーです。この共同オファーにより、お客様は企業のデータを効率的かつ効果的に保存、管理、アクセス、分析するための包括的なソリューションを利用できるようになります。
* *パフォーマンスの最適化*: NetApp のデータ ストレージに関する専門知識と Dremio のデータ処理およびデータ最適化の機能を組み合わせたパートナーシップにより、データ操作のパフォーマンスを向上させ、レイテンシを削減し、ビジネス インサイトを迅速に得るソリューションが提供されます。  Dremio は、NetApp 独自の社内 IT 分析インフラストラクチャにもパフォーマンス上のメリットをもたらしました。
* *スケーラビリティ*: Dremio とNetApp はどちらも、拡張性を考慮して設計されたソリューションを提供しています。この共同ソリューションは、顧客に高度にスケーラブルなデータ ストレージ、データ管理、および分析環境を提供します。ハイブリッド Iceberg Lakehouse 環境では、Dremio SQL クエリ エンジンとNetApp StorageGRIDを組み合わせることで、比類のないスケーラビリティ、同時実行性、クエリ パフォーマンスを実現し、あらゆるビジネスの分析ニーズに対応できます。
* *データ セキュリティとガバナンス*: 両社とも、データ セキュリティとガバナンスに重点を置いています。これらを組み合わせることで、強力なセキュリティとデータ ガバナンス機能が提供され、データが保護され、データ ガバナンスの要件が満たされることが保証されます。ロールベースのきめ細かなアクセス制御、包括的な監査、エンドツーエンドのデータ系統、統合 ID 管理、広範なコンプライアンスとセキュリティ フレームワークを備えた SSO などの機能により、企業の分析データ環境が安全に管理されます。
* *コスト効率*: Dremio のデータ レイク エンジンを NetApp のストレージ ソリューションと統合することで、顧客はデータ管理とデータ移動に関連するコストを削減できます。組織は、従来のデータ レイク環境から、 NetAppと Dremio で構成されたより最新のレイクハウス ソリューションに移行することもできます。このハイブリッド Iceberg Lakehouse ソリューションは、高速クエリ パフォーマンスと市場をリードするクエリ同時実行性を提供し、TCO を削減し、ビジネス洞察を得るまでの時間を短縮します。

