---
sidebar: sidebar 
permalink: data-analytics/hdcs-sh-use-cases.html 
keywords: summary, overview, backup, devtest, data protection 
summary: 'このセクションでは、このホワイト ペーパーの焦点となるデータ保護のユース ケースの概要を説明します。残りのセクションでは、顧客の問題 (シナリオ)、要件と課題、解決策など、各ユースケースの詳細について説明します。' 
---
= Hadoop データ保護のユースケースの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このセクションでは、このホワイト ペーパーの焦点となるデータ保護のユース ケースの概要を説明します。残りのセクションでは、顧客の問題 (シナリオ)、要件と課題、解決策など、各ユースケースの詳細について説明します。



== ユースケース1: Hadoopデータのバックアップ

このユースケースでは、 NetApp NFS ボリュームにより、大手金融機関は長いバックアップ ウィンドウ時間を 24 時間以上から数時間未満に短縮することができました。



== ユースケース 2: クラウドからオンプレミスへのバックアップと災害復旧

大手放送会社は、 NetAppを搭載したデータ ファブリックを構成要素として使用することで、オンデマンド、瞬時、Hadoop/Spark クラスターの負荷に基づくなど、さまざまなデータ転送モードに応じてクラウド データをオンプレミスのデータ センターにバックアップするという要件を満たすことができました。



== ユースケース3: 既存のHadoopデータでDevTestを有効にする

NetAppソリューションは、オンライン音楽配信会社がさまざまなブランチに複数のスペース効率の高い Hadoop クラスターを迅速に構築し、レポートを作成し、スケジュールされたポリシーを使用して毎日の DevTest タスクを実行するのに役立ちました。



== ユースケース4: データ保護とマルチクラウド接続

大手サービス プロバイダーは、 NetAppが提供するデータ ファブリックを使用して、さまざまなクラウド インスタンスから顧客にマルチクラウド分析を提供しました。



== ユースケース5: 分析ワークロードの高速化

最大規模の金融サービスおよび投資銀行の 1 社は、 NetAppネットワーク接続ストレージ ソリューションを使用して、I/O 待機時間を短縮し、定量的金融分析プラットフォームを高速化しました。
