---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-solution-overview.html 
keywords: storagegrid, splunk enterprise, smartstore, object storage, machine data 
summary: このページでは、 NetApp StorageGRID、Splunk Enterprise、Splunk SmartStore など、このソリューションを完成させるために使用されるコンポーネントについて説明します。 
---
= ソリューションの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このページでは、 NetApp StorageGRID、Splunk Enterprise、Splunk SmartStore など、このソリューションを完成させるために使用されるコンポーネントについて説明します。



== NetAppStorageGRID

NetApp StorageGRIDは、高性能でコスト効率に優れたオブジェクト ストレージ プラットフォームです。分散型のノードベースのグリッド アーキテクチャを使用して、インテリジェントでポリシー主導のグローバル データ管理を提供します。ユビキタスなグローバル オブジェクト名前空間と洗練されたデータ管理機能を組み合わせることで、ペタバイト単位の非構造化データと数十億個のオブジェクトの管理を簡素化します。シングルコールのオブジェクト アクセスはサイト全体に拡張され、高可用性アーキテクチャを簡素化するとともに、サイトまたはインフラストラクチャの停止に関係なく継続的なオブジェクト アクセスを保証します。

マルチテナンシーにより、複数のクラウドおよびエンタープライズ非構造化データ アプリケーションを同じグリッド内で安全に処理できるようになり、 StorageGRIDの ROI と使用事例が増加します。メタデータ駆動型のオブジェクト ライフサイクル ポリシーを使用して複数のサービス レベルを作成し、複数の地域にわたって耐久性、保護、パフォーマンス、および局所性を最適化できます。ユーザーは、要件の変化に応じてポリシーを調整し、中断なくデータ環境を再調整できます。

SmartStore は、 StorageGRID をリモート ストレージ層として活用し、単一のオブジェクト名前空間として提供される、地理的に分散した複数のサイトを展開して堅牢な可用性と耐久性を実現します。これにより、Splunk SmartStore は、 StorageGRIDの高パフォーマンス、高密度容量、および単一の URL を使用して複数の物理サイトにわたって数百のノードに拡張する機能を活用して、オブジェクトと対話できるようになります。この単一の URL により、単一のサイトを超えてもストレージの拡張、アップグレード、修復を中断なく実行できるようになります。  StorageGRID独自のデータ管理ポリシー エンジンは、最適化されたレベルのパフォーマンスと耐久性を提供し、データの局所性要件に準拠します。



== Splunkエンタープライズ

機械生成データの収集と分析のリーダーである Splunk は、運用分析機能を通じて IT の簡素化と近代化を支援します。また、ビジネス分析、セキュリティ、IoT のユースケースにも拡張されます。ストレージは、Splunk ソフトウェアの導入を成功させる上で重要な要素です。

機械生成データは、最も急速に成長しているタイプのビッグデータです。フォーマットは予測不可能であり、さまざまなソースから高レートかつ大量に提供されることがよくあります。これらのワークロード特性は、多くの場合、デジタル排気と呼ばれます。  Splunk SmartStore は、このデータを理解し、最もコスト効率の高いストレージ層にホット データとウォーム データを最適に配置するためのスマート データ階層化を提供します。



== Splunk スマートストア

Splunk SmartStore は、 StorageGRIDなどのオブジェクト ストレージ (リモート ストレージまたはリモート ストレージ層とも呼ばれます) を使用して、S3 プロトコルでウォーム データを保存するインデクサー機能です。

展開のデータ量が増加すると、通常、ストレージの需要がコンピュータ リソースの需要を上回ります。  SmartStore を使用すると、コンピューティングとストレージを個別に拡張することで、インデクサー ストレージとコンピューティング リソースをコスト効率よく管理できます。

SmartStore は、S3 プロトコルとキャッシュ マネージャーを使用したリモート ストレージ層を導入します。これらの機能により、データをインデクサー上のローカルまたはリモート ストレージに保存できます。インデクサー上に存在するキャッシュ マネージャーは、インデクサーとリモート ストレージ層間のデータの移動を管理します。データは、バケット メタデータとともにバケット (ホット バケットとウォーム バケット) に保存されます。

SmartStore を使用すると、ほとんどのデータがリモート ストレージ層に存在するため、インデクサーのストレージ フットプリントを最小限に抑え、I/O が最適化されたコンピューティング リソースを選択できます。インデクサーは、要求され予測された結果を返すために必要な最小限のデータ量を表すローカル キャッシュを維持します。ローカル キャッシュには、ホット バケット、アクティブまたは最近の検索に参加しているウォーム バケットのコピー、およびバケットのメタデータが含まれます。

Splunk SmartStore とStorageGRID を組み合わせることで、顧客は、高性能でコスト効率の高いリモート ストレージを使用して環境を段階的に拡張しながら、ソリューション全体に高度な弾力性を提供できます。これにより、お客様は、より多くのインデクサーが必要な場合、データ保持期間を変更する場合、または中断なく取り込み速度を上げる場合など、いつでも任意の数量のコンポーネント (ホット ストレージおよび/またはウォーム S3 ストレージ) を追加できます。
