---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-solution-benefits.html 
keywords: benefits, performance, multi-site, scalability, capacity, availability, cache 
summary: このソリューションにより、コンピューティング、ホット ストレージ、または S3 リソースを追加して、単一サイトおよび複数サイトの展開全体でのユーザー数や取り込み速度に関する需要の増大に対応できます。 
---
= このソリューションの利点
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このソリューションにより、コンピューティング、ホット ストレージ、または S3 リソースを追加して、単一サイトおよび複数サイトの展開全体でのユーザー数や取り込み速度に関する需要の増大に対応できます。

* *パフォーマンス。*  Splunk SmartStore とNetApp StorageGRID を組み合わせることで、オブジェクト ストレージを使用してホット バケットとウォーム バケット間でのデータの高速移行が可能になります。  StorageGRID は、大規模なオブジェクト ワークロードに高速なパフォーマンスを提供することで、移行プロセスを強化します。
* *マルチサイト対応。*  StorageGRID分散アーキテクチャにより、Splunk SmartStore は、データがどこに存在するかに関係なく、どのサイトからでもデータにアクセスできる単一のグローバル名前空間を通じて、単一サイトおよび複数サイトにわたる展開を拡張できます。
* *スケーラビリティが向上しました。*  Splunk 環境における変化するニーズと要求を満たすために、コンピューティング リソースとは独立してストレージ リソースを拡張し、TCO を改善します。
* *容量。*  StorageGRIDを使用すると、単一の名前空間を 560 PB 以上に拡張して、Splunk 展開で急速に増加するボリュームに対応できます。
* *データの可用性*データのビジネス価値の変化に応じて動的に調整できるメタデータ主導のポリシーを使用して、データの可用性、パフォーマンス、地理的分散、保持、保護、およびストレージ コストを最適化します。


ローカル (ホット) ストレージとリモート (ウォーム) ストレージ間のバケット コピーの転送を処理するインデクサーのコンポーネントである SmartStore キャッシュを使用してパフォーマンスを向上します。このソリューションのSplunkのサイズは、 https://docs.splunk.com/Documentation/Splunk/8.0.5/Capacity/Summaryofperformancerecommendations["Splunkが提供するガイドライン"^] 。このソリューションにより、コンピューティング、ホット ストレージ、または S3 リソースを追加して、単一サイトおよび複数サイトの展開全体でのユーザー数や取り込み速度に関する需要の増大に対応できます。
