---
settings:
  name: NetApp artificial intelligence solutions
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    lipi_enabled: true
    harmony_enabled: false
  pdf:
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions-ai.zip
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: 人工知能ソリューション
    url: "/index.html"
  - title: 新機能
    url: "/whats-new.html"
  - section: ai-infrastructures
  - section: ai-data-pipelines
  - section: ai-use-cases
  - section: data-analytics
  - title: ビデオ
    url: "/videos/ai-ml-videos.html"
  - title: ブログ
    url: "/blogs.html"
  - title: 法律上の表示
    url: "/legal-notices.html"
product-family:
  name: NetApp solutions
  repo: netapp-solutions-family
