---
sidebar: sidebar 
permalink: infra/ai-lenovo-edge-conclusion.html 
keywords: acknowledgements, additional information 
summary: AI を活用した自動化とエッジ コンピューティングは、ビジネス組織がデジタル変革を実現し、運用の効率と安全性を最大限に高めるのに役立つ主要なアプローチです。エッジ コンピューティングでは、データをデータセンターとの間で移動する必要がないため、データの処理速度が大幅に向上します。したがって、データセンターやクラウドとの間でデータを送受信する際に発生するコストが削減されます。 
---
= まとめ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
AI を活用した自動化とエッジ コンピューティングは、ビジネス組織がデジタル変革を実現し、運用の効率と安全性を最大限に高めるのに役立つ主要なアプローチです。エッジ コンピューティングでは、データをデータセンターとの間で移動する必要がないため、データの処理速度が大幅に向上します。したがって、データセンターやクラウドとの間でデータを送受信する際に発生するコストが削減されます。企業がエッジに展開された AI 推論モデルを使用してほぼリアルタイムで意思決定を行う必要がある場合、レイテンシの低減と速度の向上が有益となります。

NetAppストレージ システムは、ローカル SSD ストレージと同等以上のパフォーマンスを提供し、データ サイエンティスト、データ エンジニア、AI/ML 開発者、ビジネスまたは IT の意思決定者に次のメリットをもたらします。

* AI システム、分析、その他の重要なビジネス システム間でデータを簡単に共有できます。このデータ共有により、インフラストラクチャのオーバーヘッドが削減され、パフォーマンスが向上し、企業全体のデータ管理が合理化されます。
* コストを最小限に抑え、リソースの使用率を向上させるために、コンピューティングとストレージを独立して拡張できます。
* 統合されたスナップショット コピーとクローンを使用して合理化された開発および展開ワークフローにより、瞬時にスペース効率の高いユーザー ワークスペース、統合バージョン管理、および自動展開が実現します。
* 災害復旧と事業継続性のためのエンタープライズ グレードのデータ保護。このドキュメントで紹介されているNetAppと Lenovo のソリューションは、エッジでのエンタープライズ グレードの AI 推論の展開に最適な、柔軟なスケールアウト アーキテクチャです。




== 謝辞

* JJ  Lenovo、HPC および AI ソリューション担当シニア マネージャー、ファルカンガー氏
* Dave Arnette、 NetAppテクニカル マーケティング エンジニア
* Joey Parnell、 NetApp EシリーズAIソリューション担当テクニカルリード
* Cody Harryman、 NetAppの QA エンジニア




== 詳細情報の入手方法

このドキュメントに記載されている情報の詳細については、次のドキュメントや Web サイトを参照してください。

* NetApp AFF Aシリーズアレイ製品ページ
+
https://www.netapp.com/data-storage/aff-a-series/["https://www.netapp.com/data-storage/aff-a-series/"^]

* NetApp ONTAPデータ管理ソフトウェア - ONTAP 9 情報ライブラリ
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* TR-4727: NetApp EFシリーズの紹介
+
https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf"^]

* NetApp EシリーズSANtricityソフトウェア データシート
+
https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf["https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf"^]

* NetAppコンテナ向け永続ストレージ - NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* MLPerf
+
** https://mlcommons.org/en/["https://mlcommons.org/en/"^]
** http://www.image-net.org/["http://www.image-net.org/"^]
** https://mlcommons.org/en/news/mlperf-inference-v11/["https://mlcommons.org/en/news/mlperf-inference-v11/"^]


* NetApp BlueXPコピーと同期
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* TensorFlowベンチマーク
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* Lenovo ThinkSystem SE350 エッジサーバー
+
https://lenovopress.com/lp1168["https://lenovopress.com/lp1168"^]

* Lenovo ThinkSystem DM5100F 統合フラッシュストレージアレイ
+
https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array["https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array"]


