---
sidebar: sidebar 
permalink: software/ai-conf-protopia-usecases.html 
keywords: environmental intelligence, edge device wearables, noncombatant evacuation operations, cloud migration of analytics 
summary: デジタル画像処理には多くの利点があり、多くの組織が視覚表現に関連するデータを最大限に活用できるようになります。このNetAppと Protopia のソリューションは、ML/DL ライフサイクル全体にわたって AI/ML データを保護し、プライベート化するための独自の AI 推論設計を提供します。これにより、顧客は機密データの所有権を保持し、プライバシーに関する懸念を軽減することでパブリック クラウドまたはハイブリッド クラウドの導入モデルを使用して拡張性と効率性を高め、エッジで AI 推論を導入できるようになります。 
---
= ソリューション領域
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
デジタル画像処理には多くの利点があり、多くの組織が視覚表現に関連するデータを最大限に活用できるようになります。このNetAppと Protopia のソリューションは、ML/DL ライフサイクル全体にわたって AI/ML データを保護し、プライベート化するための独自の AI 推論設計を提供します。これにより、顧客は機密データの所有権を保持し、プライバシーに関する懸念を軽減することでパブリック クラウドまたはハイブリッド クラウドの導入モデルを使用して拡張性と効率性を高め、エッジで AI 推論を導入できるようになります。



== 環境情報

環境危険の分野で、業界が地理空間分析を活用できる方法は数多くあります。政府や公共事業局は、公衆衛生や気象状況に関する実用的な洞察を得て、パンデミックや山火事などの自然災害の際に国民に適切なアドバイスを提供できるようになります。たとえば、空港や病院などの公共の場で、感染者のプライバシーを侵害することなく COVID 陽性患者を特定し、関係当局や付近の一般の人々に必要な安全対策を警告することができます。



== エッジデバイスウェアラブル

軍隊や戦場では、エッジでの AI 推論をウェアラブル デバイスとして使用し、兵士の健康状態を追跡し、運転者の行動を監視し、兵士のプライバシーを維持し保護しながら、軍用車両に近づく際の安全性と関連するリスクについて当局に警告することができます。軍隊の未来は、戦場のモノのインターネット (IoBT) と軍事用のモノのインターネット (IoMT) によってハイテク化しており、兵士が敵を識別し、迅速なエッジ コンピューティングを使用して戦闘でより優れたパフォーマンスを発揮できるように支援するウェアラブル戦闘装備が登場しています。ドローンやウェアラブル機器などのエッジデバイスから収集された視覚データを保護し、保存することは、ハッカーや敵を寄せ付けないために非常に重要です。



== 非戦闘員避難作戦

非戦闘員避難作戦（NEO）は、生命の危険にさらされている米国市民および米国国民、国防総省の民間人、および指定された人物（ホスト国（HN）および第三国国民（TCN））を適切な安全な避難場所へ避難させるのを支援するために国防総省によって実施されます。実施されている行政管理では、主に手作業による避難者の審査プロセスが採用されています。ただし、高度に自動化された AI/ML ツールと AI/ML ビデオ難読化テクノロジーを組み合わせることで、避難者の識別、避難者の追跡、脅威のスクリーニングの精度、セキュリティ、速度が向上する可能性があります。



== ヘルスケアとバイオメディカル研究

画像処理は、コンピューター断層撮影 (CT) や磁気共鳴画像 (MRI) から取得した 3D 画像から病理を診断し、手術計画を立てるために使用されます。  HIPAA プライバシー ルールは、すべての個人情報や写真などのデジタル画像について、組織がデータを収集、処理、消去する方法を規定しています。 HIPAA セーフ ハーバー規制に基づいてデータを共有可能にするには、顔全体の写真画像およびそれに類似する画像を削除する必要があります。構造CT/MR画像から個人の顔の特徴を隠すために使用される匿名化や頭蓋骨除去アルゴリズムなどの自動化技術は、生物医学研究機関のデータ共有プロセスの不可欠な部分になっています。



== AI/ML分析のクラウド移行

従来、エンタープライズ顧客は AI/ML モデルをオンプレミスでトレーニングおよび展開してきました。規模の経済と効率性の理由から、これらの顧客は AI/ML 機能をパブリック、ハイブリッド、またはマルチクラウドのクラウド展開に移行するように拡大しています。ただし、他のインフラストラクチャに公開できるデータには制限があります。  NetAppソリューションは、次のようなあらゆるサイバーセキュリティの脅威に対応します。 https://www.netapp.com/data-protection/?internal_promo=mdw_aiml_ww_all_awareness-coas_blog["データ保護"^]セキュリティ評価も実行し、Protopia のデータ変換と組み合わせることで、画像処理 AI/ML ワークロードをクラウドに移行する際のリスクを最小限に抑えます。

他の業界におけるエッジコンピューティングとAI推論のさらなるユースケースについては、以下を参照してください。link:../infra/ai-lenovo-edge-intro.html["TR-4886 エッジにおけるAI推論"^] NetApp AIブログ https://www.netapp.com/blog/federated-learning-intelligence-vs-privacy/["知性 vs プライバシー"^]。
