---
sidebar: sidebar 
permalink: software/ai-conf-protopia-conclusion.html 
keywords: conclusion, ai inferencing, 
summary: データは、保存中、転送中、計算中の 3 つの状態で存在します。あらゆる AI 推論サービスの重要な部分は、プロセス全体を通じてデータを脅威から保護することです。推論プロセスでは外部の顧客と推論サービスを提供する企業の両方に関する個人情報が公開される可能性があるため、推論中のデータの保護は重要です。 
---
= まとめ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
データは、保存中、転送中、計算中の 3 つの状態で存在します。あらゆる AI 推論サービスの重要な部分は、プロセス全体を通じてデータを脅威から保護することです。推論プロセスでは外部の顧客と推論サービスを提供する企業の両方に関する個人情報が公開される可能性があるため、推論中のデータの保護は重要です。  Protopia AI は、今日の市場における機密 AI 推論のための、目立たないソフトウェアのみのソリューションです。 Protopia では、AI には、現在の AI/ML タスクを実行するために不可欠なデータ レコード内の変換された情報のみが供給され、それ以上は供給されません。この確率的変換はマスキングの形式ではなく、キュレーションされたノイズを使用してデータの表現を数学的に変更することに基づいています。

ONTAP機能を備えたNetAppストレージ システムは、ローカル SSD ストレージと同等以上のパフォーマンスを提供し、 NetApp DataOps Toolkit と組み合わせることで、データ サイエンティスト、データ エンジニア、AI/ML 開発者、ビジネスまたはエンタープライズ IT 意思決定者に次のメリットをもたらします。

* AI システム、分析、その他の重要なビジネス システム間でデータを簡単に共有できます。このデータ共有により、インフラストラクチャのオーバーヘッドが削減され、パフォーマンスが向上し、企業全体のデータ管理が合理化されます。
* コストを最小限に抑え、リソースの使用率を向上させるために、コンピューティングとストレージを独立して拡張できます。
* 統合されたスナップショット コピーとクローンを使用して合理化された開発および展開ワークフローにより、瞬時にスペース効率の高いユーザー ワークスペース、統合バージョン管理、および自動展開が実現します。
* 災害復旧、事業継続性、規制要件に対応したエンタープライズ グレードのデータ保護とデータ ガバナンス。
* データ管理操作の呼び出しが簡素化され、Jupyter ノートブックのNetApp DataOps Toolkit からデータ サイエンティストのワークスペースのスナップショット コピーを迅速に取得して、バックアップと追跡が可能になります。


NetAppと Protopia のソリューションは、エンタープライズ グレードの AI 推論の導入に最適な、柔軟なスケールアウト アーキテクチャを提供します。オンプレミスとハイブリッド クラウドの両方の展開において、責任ある AI プラクティスによって機密 AI 推論要件を満たすことができるため、データ保護が可能になり、機密情報のプライバシーが確保されます。
