---
sidebar: sidebar 
permalink: software/ai-nvaie-vmw-tech.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVAIE, VMware 
summary: NVIDIA AI Enterprise with NetApp and VMware - テクノロジー概要 
---
= テクノロジの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このセクションでは、 NetAppおよび VMware を使用したNVIDIA AI Enterprise のテクノロジの概要を説明します。



== NVIDIA AIエンタープライズ

NVIDIA AI Enterprise は、 NVIDIA認定システムを搭載した VMware vSphere で実行できるようにNVIDIAによって最適化、認定、サポートされている、エンドツーエンドのクラウド ネイティブな AI およびデータ分析ソフトウェア スイートです。このソフトウェアは、最新のハイブリッド クラウド環境での AI ワークロードのシンプルかつ迅速な導入、管理、スケーリングを可能にします。



== NVIDIA GPU クラウド (NGC)

NVIDIA NGC は、AI 実践者が AI ソリューションを開発できるように、GPU に最適化されたソフトウェアのカタログをホストしています。また、モデルトレーニング用のNVIDIA Base Command、モデルの展開と監視用のNVIDIA Fleet Command、独自の AI ソフトウェアに安全にアクセスして管理するための NGC Private Registry など、さまざまな AI サービスへのアクセスも提供します。また、 NVIDIA AI Enterprise のお客様は、NGC ポータルを通じてサポートをリクエストできます。



== VMware vSphere

VMware vSphere は、データセンターを CPU、ストレージ、ネットワークリソースを含む統合コンピューティング インフラストラクチャへと変革する VMware の仮想化プラットフォームです。vSphere はこれらのインフラストラクチャを統合されたオペレーティング環境として管理し、その環境に参加するデータセンターを管理するためのツールを管理者に提供します。

vSphere の 2 つのコア コンポーネントは、ESXi と vCenter Server です。  ESXiは、管理者が仮想マシンと仮想アプライアンスを作成および実行するための仮想化プラットフォームです。vCenter Serverは、管理者がネットワークに接続された複数のホストを管理し、ホストリソースをプールするためのサービスです。



== NetApp ONTAP

NetAppの最新世代のストレージ管理ソフトウェアであるONTAP 9 により、企業はインフラストラクチャを最新化し、クラウド対応のデータセンターに移行できるようになります。 ONTAP は業界をリードするデータ管理機能を活用し、データの保存場所に関係なく、単一のツール セットでデータの管理と保護を可能にします。また、エッジ、コア、クラウドなど、必要な場所にデータを自由に移動することもできます。  ONTAP 9 には、データ管理を簡素化し、重要なデータを高速化および保護し、ハイブリッド クラウド アーキテクチャ全体で次世代のインフラストラクチャ機能を実現する多数の機能が含まれています。



=== データ管理を簡素化

データ管理は、AI アプリケーションと AI/ML データセットのトレーニングに適切なリソースが使用されるように、企業の IT 運用とデータ サイエンティストにとって非常に重要です。  NetAppテクノロジーに関する次の追加情報は、この検証の範囲外ですが、導入によっては関連する可能性があります。

ONTAPデータ管理ソフトウェアには、運用を合理化および簡素化し、総運用コストを削減するための次の機能が含まれています。

* インライン データ圧縮と拡張重複排除。データ圧縮によりストレージ ブロック内の無駄なスペースが削減され、重複排除により実効容量が大幅に増加します。これは、ローカルに保存されたデータとクラウドに階層化されたデータに適用されます。
* 最小、最大、および適応型サービス品質 (AQoS)。きめ細かなサービス品質 (QoS) 制御により、高度に共有された環境における重要なアプリケーションのパフォーマンス レベルを維持できます。
* NetAppFabricPool。  Amazon Web Services (AWS)、Azure、 NetApp StorageGRIDストレージ ソリューションなどのパブリックおよびプライベート クラウド ストレージ オプションへのコールド データの自動階層化を提供します。  FabricPoolの詳細については、以下を参照してください。 https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["TR-4598: FabricPool のベストプラクティス"^] 。




=== データの高速化と保護

ONTAP は優れたレベルのパフォーマンスとデータ保護を提供し、これらの機能を次のように拡張します。

* パフォーマンスと低レイテンシ。  ONTAP は、可能な限り低いレイテンシで最高のスループットを提供します。
* データ保護：ONTAP は、すべてのプラットフォームにわたる共通管理を備えた組み込みのデータ保護機能を提供します。
* NetAppボリューム暗号化 (NVE)。  ONTAP は、オンボードと外部キー管理の両方をサポートするネイティブのボリューム レベルの暗号化を提供します。
* マルチテナントと多要素認証。  ONTAP は、最高レベルのセキュリティでインフラストラクチャ リソースを共有できるようにします。




=== 将来を見据えたインフラ

ONTAP は、次の機能により、要求が厳しく常に変化するビジネス ニーズへの対応に役立ちます。

* シームレスなスケーリングと中断のない運用。 ONTAP は、既存のコントローラおよびスケールアウト クラスタへの無停止の容量追加をサポートします。お客様は、コストのかかるデータ移行や停止なしで、NVMe や 32Gb FC などの最新テクノロジーにアップグレードできます。
* クラウド接続。  ONTAP は、すべてのパブリック クラウドでソフトウェア定義ストレージ (ONTAP Select) とクラウド ネイティブ インスタンス (Google Cloud NetApp Volumes) のオプションを備えた、最もクラウドに接続されたストレージ管理ソフトウェアです。
* 新しいアプリケーションとの統合。  ONTAP は、既存のエンタープライズ アプリケーションをサポートするのと同じインフラストラクチャを使用して、自律走行車、スマート シティ、インダストリー 4.0 などの次世代プラットフォームとアプリケーション向けにエンタープライズ グレードのデータ サービスを提供します。




== NetApp DataOps ツールキット

NetApp DataOps Toolkit は、高性能なスケールアウトNetAppストレージを基盤とする開発/トレーニング ワークスペースと推論サーバーの管理を簡素化する Python ベースのツールです。主な機能は次のとおりです。

* 高性能のスケールアウトNetAppストレージを活用した新しい大容量の JupyterLab ワークスペースを迅速にプロビジョニングします。
* エンタープライズ クラスのNetAppストレージを活用した新しいNVIDIA Triton Inference Server インスタンスを迅速にプロビジョニングします。
* 実験や迅速な反復を可能にするために、大容量の JupyterLab ワークスペースをほぼ瞬時に複製します。
* バックアップやトレーサビリティ/ベースライン作成のために、大容量の JupyterLab ワークスペースのスナップショットをほぼ瞬時に保存します。
* 大容量、高パフォーマンスのデータ ボリュームをほぼ瞬時にプロビジョニング、クローン作成、スナップショット作成します。

