---
sidebar: sidebar 
permalink: software/ai-osmlops-trident-ops.html 
keywords: Trident 
summary: NetAppを使用したオープンソース MLOps - Tridentオペレーションの例 
---
= Trident操作の例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このセクションには、 Tridentで実行するさまざまな操作の例が含まれています。



== 既存のボリュームをインポートする

Kubernetes クラスター内のコンテナーにマウントするが、クラスター内の PVC に関連付けられていない既存のボリュームがNetAppストレージ システム/プラットフォーム上に存在する場合は、これらのボリュームをインポートする必要があります。これらのボリュームをインポートするには、 Tridentボリューム インポート機能を使用できます。

以下のコマンド例は、 `pb_fg_all` 。 PVCの詳細については、 https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Kubernetesの公式ドキュメント"^] 。ボリュームインポート機能の詳細については、 https://docs.netapp.com/us-en/trident/index.html["Tridentのドキュメント"^] 。

アン `accessModes`の価値 `ReadOnlyMany`サンプルの PVC 仕様ファイルで指定されています。詳細については、 `accessMode`フィールドについては、 https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Kubernetesの公式ドキュメント"^] 。

....
$ cat << EOF > ./pvc-import-pb_fg_all-iface1.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pb-fg-all-iface1
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ontap-ai-flexgroups-retain-iface1
EOF
$ tridentctl import volume ontap-ai-flexgroups-iface1 pb_fg_all -f ./pvc-import-pb_fg_all-iface1.yaml -n trident
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
|          NAME                  |  SIZE  |       STORAGE CLASS               | PROTOCOL |             BACKEND UUID                         | STATE  | MANAGED |
+--------------------------------+--------+-----------------------------------+----------+------------------------------------------+--------+---------+
| default-pb-fg-all-iface1-7d9f1 | 10 TiB | ontap-ai-flexgroups-retain-iface1 | file     | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online | true    |
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
$ tridentctl get volume -n trident
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
|               NAME               |  SIZE   |           STORAGE CLASS           | PROTOCOL |             BACKEND UUID             | STATE  | MANAGED |
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
| default-pb-fg-all-iface1-7d9f1   | 10 TiB  | ontap-ai-flexgroups-retain-iface1 | file     | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online | true    |
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
$ kubectl get pvc
NAME                 STATUS   VOLUME                             CAPACITY         ACCESS MODES   STORAGECLASS                        AGE
pb-fg-all-iface1     Bound    default-pb-fg-all-iface1-7d9f1     10995116277760   ROX            ontap-ai-flexgroups-retain-iface1   25h
....


== 新しいボリュームをプロビジョニングする

Tridentを使用して、 NetAppストレージ システムまたはプラットフォームに新しいボリュームをプロビジョニングできます。



=== kubectl を使用して新しいボリュームをプロビジョニングする

次のコマンド例は、kubectl を使用して新しいFlexVol volumeをプロビジョニングする方法を示しています。

アン `accessModes`の価値 `ReadWriteMany`次のサンプル PVC 定義ファイルで指定されています。詳細については、 `accessMode`フィールドについては、 https://kubernetes.io/docs/concepts/storage/persistent-volumes/["Kubernetesの公式ドキュメント"^] 。

....
$ cat << EOF > ./pvc-tensorflow-results.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tensorflow-results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ontap-ai-flexvols-retain
EOF
$ kubectl create -f ./pvc-tensorflow-results.yaml
persistentvolumeclaim/tensorflow-results created
$ kubectl get pvc
NAME                              STATUS    VOLUME                             CAPACITY         ACCESS MODES   STORAGECLASS                        AGE
pb-fg-all-iface1                  Bound     default-pb-fg-all-iface1-7d9f1     10995116277760   ROX            ontap-ai-flexgroups-retain-iface1   26h
tensorflow-results                Bound     default-tensorflow-results-2fd60   1073741824       RWX            ontap-ai-flexvols-retain            25h
....


=== NetApp DataOps ツールキットを使用して新しいボリュームをプロビジョニングする

NetApp DataOps Toolkit for Kubernetes を使用して、 NetAppストレージ システムまたはプラットフォームに新しいボリュームをプロビジョニングすることもできます。 NetApp DataOps Toolkit for Kubernetes は、 Tridentを使用してボリュームをプロビジョニングしますが、ユーザーのプロセスを簡素化します。参照link:https://github.com/NetApp/netapp-dataops-toolkit/blob/main/netapp_dataops_k8s/docs/volume_management.md["ドキュメント"]詳細については。
