---
sidebar: sidebar 
permalink: vector-db/ai-vdb-overview.html 
keywords: Solution Overview vector database 
summary: NetApp向けベクトルデータベースソリューションの概要 
---
= ソリューションの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このセクションでは、 NetAppベクトル データベース ソリューションの概要を説明します。



== ソリューションの概要

このソリューションは、ベクター データベースのお客様が直面する課題に対処するためにNetAppが提供する独自の利点と機能を紹介します。 NetApp ONTAP、 StorageGRID、NetApp のクラウド ソリューション、 SnapCenterを活用することで、お客様はビジネス運営に大きな価値を加えることができます。これらのツールは、既存の問題に対処するだけでなく、効率性と生産性を向上させ、ビジネス全体の成長に貢献します。



=== NetAppを選ぶ理由

* ONTAPやStorageGRIDなどの NetApp の製品は、ストレージとコンピューティングの分離を可能にし、特定の要件に基づいて最適なリソース利用を実現します。この柔軟性により、お客様はNetAppストレージ ソリューションを使用してストレージを独自に拡張できるようになります。
* NetApp のストレージ コントローラを活用することで、顧客は NFS および S3 プロトコルを使用してベクター データベースにデータを効率的に提供できます。これらのプロトコルは、顧客データの保存を容易にし、ベクター データベース インデックスを管理するため、ファイルやオブジェクトの方法を通じてアクセスされるデータの複数のコピーが不要になります。
* NetApp ONTAP は、AWS、Azure、Google Cloud などの主要なクラウド サービス プロバイダー全体で NAS およびオブジェクト ストレージのネイティブ サポートを提供します。この幅広い互換性により、シームレスな統合が保証され、顧客データのモビリティ、グローバルなアクセス性、災害復旧、動的なスケーラビリティ、および高パフォーマンスが実現します。
* NetApp の強力なデータ管理機能により、お客様はデータが潜在的なリスクや脅威から十分に保護されていることを確信できます。  NetApp はデータ セキュリティを最優先し、お客様の貴重な情報の安全性と整合性に関して安心を提供します。

