---
sidebar: sidebar 
permalink: vector-db/ai-vdb-intro.html 
keywords: vector database 
summary: NetApp向けベクターデータベースソリューションの紹介 
---
= はじめに
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このセクションでは、 NetAppのベクトル データベース ソリューションについて紹介します。



== はじめに

ベクター データベースは、大規模言語モデル (LLM) と生成型人工知能 (AI) におけるセマンティック検索の複雑さを処理するために設計された課題に効果的に対処します。従来のデータ管理システムとは異なり、ベクター データベースは、ラベルやタグではなくデータ自体のコンテンツを使用して、画像、ビデオ、テキスト、オーディオ、その他の非構造化データなど、さまざまな種類のデータを処理および検索できます。

リレーショナル データベース管理システム (RDBMS) の限界、特に AI アプリケーションで一般的な高次元データ表現や非構造化データに関する問題点は、十分に文書化されています。 RDBMS では、データをより管理しやすい構造にフラット化するという時間がかかり、エラーが発生しやすいプロセスが必要になることが多く、検索の遅延や非効率につながります。しかし、ベクター データベースはこれらの問題を回避するように設計されており、複雑で高次元のデータを管理および検索するためのより効率的で正確なソリューションを提供し、AI アプリケーションの進歩を促進します。

このドキュメントは、現在ベクター データベースを使用しているか、使用を計画しているお客様向けの包括的なガイドとして機能し、 NetApp ONTAP、 NetApp StorageGRID、 Amazon FSx ONTAP for NetApp ONTAP、 SnapCenterなどのプラットフォームでベクター データベースを活用するためのベスト プラクティスを詳しく説明します。ここで提供されるコンテンツは、さまざまなトピックをカバーしています。

* NetApp ONTAPおよびStorageGRIDオブジェクト ストレージを通じてNetAppストレージによって提供される、Milvus などのベクター データベース向けのインフラストラクチャ ガイドライン。
* ファイルおよびオブジェクト ストアを介して AWS FSx ONTAPの Milvus データベースを検証します。
* NetApp のファイルとオブジェクトの二重性を詳しく調べ、ベクター データベースやその他のアプリケーションのデータに対するその有用性を示します。
* NetApp のデータ保護管理製品SnapCenter が、ベクター データベース データのバックアップと復元機能をどのように提供するかについて説明します。
* NetApp のハイブリッド クラウドがオンプレミスとクラウド環境全体でデータ レプリケーションと保護を提供する仕組みについて説明します。
* NetApp ONTAP上の Milvus や pgvector などのベクトル データベースのパフォーマンス検証に関する洞察を提供します。
* 2 つの具体的な使用例: 大規模言語モデル (LLM) を使用した検索拡張生成 (RAG) とNetApp IT チームの ChatAI。これにより、概説した概念と実践の実際的な例が提供されます。

